/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-06-19 00:18:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import shg.bean.StateBean;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("shg.bean.StateBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("    ");
      shg.master.StateDAO ob = null;
      ob = (shg.master.StateDAO) _jspx_page_context.getAttribute("ob", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (ob == null){
        ob = new shg.master.StateDAO();
        _jspx_page_context.setAttribute("ob", ob, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("/* function getAdharDetail() {\r\n");
      out.write("\t\r\n");
      out.write("var adhar=document.getElementById(\"adhar\").value;\r\n");
      out.write("  var xmlhttp;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("if (window.XMLHttpRequest)\r\n");
      out.write("{\r\n");
      out.write("// code for IE7+, Firefox, Chrome, Opera, Safari\r\n");
      out.write("     xmlhttp=new XMLHttpRequest();\r\n");
      out.write("}\r\n");
      out.write("else\r\n");
      out.write("{// code for IE6, IE5\r\n");
      out.write(" xmlhttp=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" xmlhttp.onreadystatechange=function()\r\n");
      out.write(" {\r\n");
      out.write(" if (xmlhttp.readyState==4 && xmlhttp.status==200)\r\n");
      out.write("{\r\n");
      out.write("//document.getElementById(\"fname\").value\r\n");
      out.write(" var s=xmlhttp.responseText;\r\n");
      out.write("       t=s.split(\",\");\r\n");
      out.write("     document.getElementById(\"t1\").value=t[0];\r\n");
      out.write("     document.getElementById(\"t2\").value=t[1];\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write(" }\r\n");
      out.write("  xmlhttp.open(\"GET\",\"AdharServlet?adhar=\"+adhar,true);\r\n");
      out.write("      xmlhttp.send();\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getDistrictName() {\r\n");
      out.write("var sCode=document.getElementById(\"stateCode\").value;\r\n");
      out.write("  var xmlhttp;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("if (window.XMLHttpRequest)\r\n");
      out.write("{\r\n");
      out.write("// code for IE7+, Firefox, Chrome, Opera, Safari\r\n");
      out.write("     xmlhttp=new XMLHttpRequest();\r\n");
      out.write("}\r\n");
      out.write("else\r\n");
      out.write("{// code for IE6, IE5\r\n");
      out.write(" xmlhttp=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write(" }\r\n");
      out.write(" xmlhttp.onreadystatechange=function()\r\n");
      out.write(" {\r\n");
      out.write(" if (xmlhttp.readyState==4 && xmlhttp.status==200)\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("document.getElementById(\"print\").value=xmlhttp.responseText;\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write(" }\r\n");
      out.write("  xmlhttp.open(\"GET\",\"StateMasterServlet?sCode=\"+sCode,true);\r\n");
      out.write("      xmlhttp.send();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("   function addRow()\r\n");
      out.write("   {\r\n");
      out.write("   var table=document.getElementById(\"child\");\r\n");
      out.write("   var rowCount=table.rows.length;\r\n");
      out.write("   var row=table.insertRow(rowCount);\r\n");
      out.write("   var cell1=row.insertCell(0);\r\n");
      out.write("   cell1.innerHTML=rowCount-1;\r\n");
      out.write("   var cell2=row.insertCell(1);\r\n");
      out.write("   \r\n");
      out.write("   var element2=document.createElement(\"input\");\r\n");
      out.write("   element2.type=\"checkbox\";\r\n");
      out.write("   element2.name=\"chk\";\r\n");
      out.write("   cell2.appendChild(element2);\r\n");
      out.write("   var cell3=row.insertCell(2);\r\n");
      out.write("   \r\n");
      out.write("   var element3=document.createElement(\"input\");\r\n");
      out.write("   element3.type=\"text\";\r\n");
      out.write("   element3.name=\"cname\";\r\n");
      out.write("   cell3.appendChild(element3);\r\n");
      out.write("   var cell4=row.insertCell(3);\r\n");
      out.write("   \r\n");
      out.write("   var element4=document.createElement(\"input\");\r\n");
      out.write("   element4.type=\"text\";\r\n");
      out.write("   element4.name=\"age\";\r\n");
      out.write("   cell4.appendChild(element4);\r\n");
      out.write("   var cell5=row.insertCell(4);\r\n");
      out.write("   \r\n");
      out.write("   var element5=document.createElement(\"Select\");\r\n");
      out.write("   element5.name=\"gender\";\r\n");
      out.write("   var option = document.createElement(\"OPTION\");\r\n");
      out.write("   option.innerHTML = \"Male\";\r\n");
      out.write("   option.value=\"Male\";\r\n");
      out.write("   element5.options.add(option);\r\n");
      out.write("   var option = document.createElement(\"OPTION\");\r\n");
      out.write("   option.innerHTML = \"Female\";\r\n");
      out.write("   option.value=\"Female\";\r\n");
      out.write("   element5.options.add(option);\r\n");
      out.write("   cell5.appendChild(element5);\r\n");
      out.write("   var cell6=row.insertCell(5);\r\n");
      out.write("   \r\n");
      out.write("   var element6=document.createElement(\"input\");\r\n");
      out.write("   element6.type=\"text\";\r\n");
      out.write("   element6.name=\"cadhar\"; \r\n");
      out.write("   cell6.appendChild(element6);\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   function deleteRow()\r\n");
      out.write("   {\r\n");
      out.write("     var table=document.getElementById(\"child\");\r\n");
      out.write("     var rowCount=table.rows.length;\r\n");
      out.write("\t for(var i=3;i<rowCount;i++)\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t  var row=table.rows[i];\r\n");
      out.write("\t\t  var chkbox = row.cells[1].childNodes[0];\r\n");
      out.write("\t\t  if(chkbox != null && chkbox.checked == true)\r\n");
      out.write("\t\t    {\r\n");
      out.write("\t\t\t\ttable.deleteRow(i);\r\n");
      out.write("\t\t\t\trowCount--;\r\n");
      out.write("\t\t\t\ti--;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   function getAllDistrict(stCode)\r\n");
      out.write("   {\r\n");
      out.write("\t   var req;    \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t  if (window.XMLHttpRequest)\r\n");
      out.write("\t\t  \t{\r\n");
      out.write("\t\t  \t     // code for IE7+, Firefox, Chrome, Opera, Safari\r\n");
      out.write("\t\t  \t     req=new XMLHttpRequest();\r\n");
      out.write("\t\t  \t}\r\n");
      out.write("\t\t  \telse\r\n");
      out.write("\t\t  \t{    // code for IE6, IE5\r\n");
      out.write("\t\t  \t     req=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t  \t }\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  req.onreadystatechange = function() {\r\n");
      out.write("\t\t\t    if (this.readyState == 4 && this.status == 200) {\r\n");
      out.write("\t\t\t      document.getElementById(\"select_District\").innerHTML = this.responseText;\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t  };\r\n");
      out.write("\t\t\t  req.open(\"GET\", \"District_Servlet?stCode=\"+stCode, true);\r\n");
      out.write("\t\t\t  req.send();\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   function getBankDetail(ifsc)\r\n");
      out.write("   {\r\n");
      out.write("\t   var req;    \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t  if (window.XMLHttpRequest)\r\n");
      out.write("\t\t  \t{\r\n");
      out.write("\t\t  \t     // code for IE7+, Firefox, Chrome, Opera, Safari\r\n");
      out.write("\t\t  \t     req=new XMLHttpRequest();\r\n");
      out.write("\t\t  \t}\r\n");
      out.write("\t\t  \telse\r\n");
      out.write("\t\t  \t{    // code for IE6, IE5\r\n");
      out.write("\t\t  \t     req=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t  \t }\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  req.onreadystatechange = function() {\r\n");
      out.write("\t\t\t    if (this.readyState == 4 && this.status == 200) {\r\n");
      out.write("\t\t\t      document.getElementById(\"bankDetail\").innerHTML = this.responseText;\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t  };\r\n");
      out.write("\t\t\t  req.open(\"GET\", \"Bank_Detail_Servlet?ifsc=\"+ifsc, true);\r\n");
      out.write("\t\t\t  req.send();\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   function validateAdharAndAge()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar age = document.getElementById(\"cAge\").value;\r\n");
      out.write("\t\tvar adhar = document.getElementById(\"cAdhar\").value;\r\n");
      out.write("\t\tif (age >= 18 && age <= 60)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(adhar.length==12)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Your Aadhar Number is not valid...\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"Your Age is not between 18 to 60\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"ChildParentDetails\" method=\"post\" onsubmit=\"return validateAdharAndAge()\">\r\n");
      out.write("<table id=\"parent\" bgcolor=\"yellowgreen\" border =\"3\">\r\n");
      out.write("<tr>\r\n");
      out.write("  <th colspan=\"4\" align=\"center\">Self Help Group</th>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr >    \r\n");
      out.write("<th>Group Name :</th><td><input type=\"text\" name=\"gname\" ></td></tr>\r\n");
      out.write("<tr><th>Account No :</th><td><input type=\"text\" name=\"an\"></td>\r\n");
      out.write("<th>IFSC :</th><td><input type=\"text\" name=\"ifsc\"  id=\"ifsc\" onblur=\"getBankDetail(this.value);\"></td></tr>\r\n");
      out.write("<tr id=\"bankDetail\"></tr>\r\n");
      out.write("\r\n");
      out.write("<tr><th>State Name</th><td><select name=\"stateCode\" onchange=\"getAllDistrict(this.value)\">\r\n");
      out.write("                                  <option value=\"0\">select state</option>\r\n");
      out.write("                                  \r\n");


         List<StateBean> list=ob.getStateDetails();
                                  
                                  for(StateBean p:list)
                                  {                         

      out.write("\r\n");
      out.write("\r\n");
      out.write("<option value=\"");
      out.print(p.getStCode());
      out.write("\" > ");
      out.print(p.getStName());
      out.write(" </option>\r\n");
      out.write("                                  \r\n");
      out.write("                                  ");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t  </select></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<th>District Name</th>\r\n");
      out.write("                      <td><select name=\"districtCode\" id=\"select_District\">\r\n");
      out.write("                      \r\n");
      out.write("                                   <option value=\"0\">select District</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t\t  </select></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table id=\"child\" bgcolor=\"yellow\" border =\"3\">\r\n");
      out.write("  <tr>\r\n");
      out.write("   <th colspan=\"4\" align=\"center\">Member's Detail </th>\r\n");
      out.write("   <th align=\"right\"> <input type=\"button\" id=\"b1\"  onclick=\"addRow();\">Add More Member</th>\r\n");
      out.write("   <th align=\"right\"> <input type=\"button\" id=\"b2\"  onclick=\"deleteRow();\">Remove Member</th>\r\n");
      out.write("</tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("     <th>S.No.</th><th>Select</th><th>Member Name</th><th>Age</th><th>Gender</th><th>Aadhar</th>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("     <td>1</td><td><input type=\"checkbox\" name=\"chk\"></td>\r\n");
      out.write("     <td><input type=\"text\" name=\"cname\"></td>\r\n");
      out.write("     <td><input type=\"text\" name=\"age\" id=\"cAge\"></td>\r\n");
      out.write("     <td><select name=\"select_gender\">\r\n");
      out.write("                         <option value=\"0\">select</option>\r\n");
      out.write("                         <option value=\"Male\">Male</option>\r\n");
      out.write("                                  <option value=\"Female\">Female</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  </select></td>\r\n");
      out.write("     <td><input type=\"text\" name=\"cadhar\" id=\"cAdhar\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("</table>\r\n");
      out.write("<table>\r\n");
      out.write("<tr><td><input type=\"submit\" value=\"Save\"></td>\r\n");
      out.write("<td><a href=ViewChildParentDetails>View</a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
