<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://soa" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://soa" xmlns:intf="http://soa" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://soa" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="getStateDetailsReturn" type="xsd:string"/>
  </schema>
 </wsdl:types>

   <wsdl:message name="getStateDetailsRequest">

   </wsdl:message>

   <wsdl:message name="getStateDetailsResponse">

      <wsdl:part element="impl:getStateDetailsReturn" name="getStateDetailsReturn">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="RequestHandler">

      <wsdl:operation name="getStateDetails">

         <wsdl:input message="impl:getStateDetailsRequest" name="getStateDetailsRequest">

       </wsdl:input>

         <wsdl:output message="impl:getStateDetailsResponse" name="getStateDetailsResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="RequestHandlerSoapBinding" type="impl:RequestHandler">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="getStateDetails">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="getStateDetailsRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="getStateDetailsResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="RequestHandlerService">

      <wsdl:port binding="impl:RequestHandlerSoapBinding" name="RequestHandler">

         <wsdlsoap:address location="http://localhost:8080/RestApi_SOA_Server_07June/services/RequestHandler"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
